CREATE DATABASE ShopPC_data
ON
(	NAME = 'ShopPC_data',
	FILENAME = 'C:\Code\ShopPC_data.mdf',
	SIZE = 10MB,
	MAXSIZE = 100MB,
	FILEGROWTH = 5MB
)
LOG ON
(	NAME = 'ShopPC_log',
	FILENAME = 'C:\Code\ShopPC_data.ldf',
	SIZE = 5MB,
	MAXSIZE = 50MB,
	FILEGROWTH = 5MB
)
GO

USE ShopPC_data;
GO

CREATE TABLE TheLoai(
	MaTL INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	TenTL NVARCHAR(100) NOT NULL,
	MoTaTL NTEXT
)
GO

CREATE TABLE SanPham(
	MaSP INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	TenSP NVARCHAR(255) NOT NULL,
	MaTL INT,
	DonGiaSP MONEY,
	TonKhoSP SMALLINT,
	Chip VARCHAR(50),
	Main VARCHAR(100),
	VGA VARCHAR(50),
	NhanSanXuat VARCHAR(50),
	RAM VARCHAR(100),
	AnhSP TEXT,
	FOREIGN KEY(MaTL) REFERENCES TheLoai(MaTL)
)
GO

CREATE TABLE NhanVien(
	MaNV VARCHAR(255) NOT NULL PRIMARY KEY,
	PassNV VARCHAR(255),
	HoLotNV NVARCHAR(20) NOT NULL,
	TenNV NVARCHAR(10) NOT NULL,
	DiaChiNV NVARCHAR(60),
	SdtNV NVARCHAR(24),
	AnhNV IMAGE,
	GhiChu NTEXT
)
GO

CREATE TABLE KhachHang(
	MaKH VARCHAR(255) NOT NULL PRIMARY KEY,
	PassKH VARCHAR(255),
	TenLienHe NVARCHAR(30) NOT NULL,
	DiaChi NVARCHAR(60),
	Sdt NVARCHAR(24)
)
GO

CREATE TABLE HoaDon(
	MaHD INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	MaKH VARCHAR(255),
	MaNV VARCHAR(255),	
	DiaChiShip NVARCHAR(60),
	SdtShip VARCHAR(24),
	NgayDatHang DATE,
	GhiChu TEXT,
	FOREIGN KEY(MaKH) REFERENCES KhachHang(MaKH),
	FOREIGN KEY(MaNV) REFERENCES NhanVien(MaNV)
)
GO

CREATE TABLE ChiTietHoaDon(
	MaHD INT,
	MaSP INT,
	SoLuong SMALLINT,
	GiamGia FLOAT,
	PRIMARY KEY (MaHD, MaSP),
	FOREIGN KEY(MaHD) REFERENCES HoaDon(MaHD),
	FOREIGN KEY(MaSP) REFERENCES SanPham(MaSP)
)
GO
